name: base
channels:
  - defaults
dependencies:
  - _libgcc_mutex=0.1=main
  - _openmp_mutex=5.1=1_gnu
  - anaconda-anon-usage=0.7.1=py313hfc0e8ea_100
  - annotated-types=0.6.0=py313h06a4308_0
  - anyio=4.7.0=py313h06a4308_0
  - archspec=0.2.3=pyhd3eb1b0_0
  - blas=1.0=mkl
  - boltons=24.1.0=py313h06a4308_0
  - brotli-python=1.0.9=py313h6a678d5_9
  - bzip2=1.0.8=h5eee18b_6
  - c-ares=1.19.1=h5eee18b_0
  - ca-certificates=2025.2.25=h06a4308_0
  - certifi=2025.6.15=py313h06a4308_0
  - cffi=1.17.1=py313h1fdaa30_1
  - charset-normalizer=3.3.2=pyhd3eb1b0_0
  - conda=25.5.1=py313h06a4308_0
  - conda-anaconda-telemetry=0.1.2=py313h06a4308_1
  - conda-anaconda-tos=0.2.0=py313h06a4308_0
  - conda-content-trust=0.2.0=py313h06a4308_1
  - conda-libmamba-solver=25.4.0=pyhd3eb1b0_0
  - conda-package-handling=2.4.0=py313h06a4308_0
  - conda-package-streaming=0.11.0=py313h06a4308_0
  - cpp-expected=1.1.0=hdb19cb5_0
  - cryptography=45.0.3=py313h2ccb017_0
  - deprecated=1.2.13=py313h06a4308_0
  - distro=1.9.0=py313h06a4308_0
  - expat=2.7.1=h6a678d5_0
  - filelock=3.17.0=py313h06a4308_0
  - fmt=9.1.0=hdb19cb5_1
  - frozendict=2.4.2=py313h06a4308_0
  - gmp=6.3.0=h6a678d5_0
  - gmpy2=2.2.1=py313h5eee18b_0
  - h11=0.16.0=py313h06a4308_0
  - httpcore=1.0.9=py313h06a4308_0
  - httpx=0.28.1=py313h06a4308_0
  - icu=73.1=h6a678d5_0
  - idna=3.7=py313h06a4308_0
  - importlib-metadata=8.5.0=py313h06a4308_0
  - intel-openmp=2023.1.0=hdb19cb5_46306
  - jinja2=3.1.6=py313h06a4308_0
  - jsonpatch=1.33=py313h06a4308_1
  - jsonpointer=2.1=pyhd3eb1b0_0
  - krb5=1.20.1=h143b758_1
  - ld_impl_linux-64=2.40=h12ee557_0
  - libabseil=20250127.0=cxx17_h6a678d5_0
  - libarchive=3.7.7=hfab0078_0
  - libcurl=8.12.1=hc9e6f67_0
  - libedit=3.1.20230828=h5eee18b_0
  - libev=4.33=h7f8727e_1
  - libffi=3.4.4=h6a678d5_1
  - libgcc-ng=11.2.0=h1234567_1
  - libgomp=11.2.0=h1234567_1
  - libmamba=2.0.5=haf1ee3a_1
  - libmambapy=2.0.5=py313hdb19cb5_1
  - libmpdec=4.0.0=h5eee18b_0
  - libnghttp2=1.57.0=h2d74bed_0
  - libprotobuf=5.29.3=h3cdef7c_1
  - libsolv=0.7.30=he621ea3_1
  - libssh2=1.11.1=h251f7ec_0
  - libstdcxx-ng=11.2.0=h1234567_1
  - libtorch=2.6.0=cpu_mkl_h881e62d_106
  - libuuid=1.41.5=h5eee18b_0
  - libuv=1.48.0=h5eee18b_0
  - libxcb=1.17.0=h9b100fa_0
  - libxml2=2.13.8=hfdd30dd_0
  - lz4-c=1.9.4=h6a678d5_1
  - markdown-it-py=2.2.0=py313h06a4308_1
  - markupsafe=3.0.2=py313h5eee18b_0
  - mdurl=0.1.0=py313h06a4308_0
  - menuinst=2.2.0=py313h06a4308_1
  - mkl=2023.1.0=h213fc3f_46344
  - mkl-service=2.4.0=py313h5eee18b_2
  - mkl_fft=1.3.11=py313h5eee18b_0
  - mkl_random=1.2.8=py313h06d7b56_0
  - mpc=1.3.1=h5eee18b_0
  - mpfr=4.2.1=h5eee18b_0
  - mpmath=1.3.0=py313h06a4308_0
  - ncurses=6.4=h6a678d5_0
  - networkx=3.4.2=py313h06a4308_0
  - nlohmann_json=3.11.2=h6a678d5_0
  - numpy=2.3.1=py313h8d96ed3_0
  - numpy-base=2.3.1=py313h8e760e0_0
  - openssl=3.0.16=h5eee18b_0
  - opentelemetry-api=1.30.0=py313h06a4308_0
  - packaging=24.2=py313h06a4308_0
  - pcre2=10.42=hebb0a14_1
  - pip=25.1=pyhc872135_2
  - platformdirs=4.3.7=py313h06a4308_0
  - pluggy=1.5.0=py313h06a4308_0
  - pthread-stubs=0.3=h0ce48e5_1
  - pybind11-abi=5=hd3eb1b0_0
  - pycosat=0.6.6=py313h5eee18b_2
  - pycparser=2.21=pyhd3eb1b0_0
  - pydantic=2.10.3=py313h06a4308_0
  - pydantic-core=2.27.1=py313h4aa5aa6_0
  - pygments=2.19.1=py313h06a4308_0
  - pysocks=1.7.1=py313h06a4308_0
  - python=3.13.5=h4612cfd_100_cp313
  - python_abi=3.13=0_cp313
  - pytorch=2.6.0=cpu_mkl_py313hfd6889d_106
  - readline=8.2=h5eee18b_0
  - reproc=14.2.4=h6a678d5_2
  - reproc-cpp=14.2.4=h6a678d5_2
  - rich=13.9.4=py313h06a4308_0
  - ruamel.yaml=0.18.10=py313h5eee18b_0
  - ruamel.yaml.clib=0.2.12=py313h5eee18b_0
  - setuptools=72.1.0=py313h06a4308_0
  - simdjson=3.10.1=hdb19cb5_0
  - sleef=3.5.1=h5eee18b_2
  - sniffio=1.3.0=py313h06a4308_0
  - spdlog=1.11.0=hdb19cb5_0
  - sqlite=3.45.3=h5eee18b_0
  - sympy=1.13.3=py313h06a4308_1
  - tbb=2021.8.0=hdb19cb5_0
  - tk=8.6.14=h993c535_1
  - tqdm=4.67.1=py313h7040dfc_0
  - truststore=0.10.0=py313h06a4308_0
  - typing-extensions=4.12.2=py313h06a4308_0
  - typing_extensions=4.12.2=py313h06a4308_0
  - urllib3=2.3.0=py313h06a4308_0
  - wheel=0.45.1=py313h06a4308_0
  - wrapt=1.17.0=py313h5eee18b_0
  - xorg-libx11=1.8.12=h9b100fa_1
  - xorg-libxau=1.0.12=h9b100fa_0
  - xorg-libxdmcp=1.1.5=h9b100fa_0
  - xorg-xorgproto=2024.1=h5eee18b_1
  - xz=5.6.4=h5eee18b_1
  - yaml-cpp=0.8.0=h6a678d5_1
  - zipp=3.21.0=py313h06a4308_0
  - zlib=1.2.13=h5eee18b_1
  - zstandard=0.23.0=py313h2c38b39_1
  - zstd=1.5.6=hc292b87_0
  - pip:
      - aiohappyeyeballs==2.6.1
      - aiohttp==3.12.14
      - aiosignal==1.4.0
      - attrs==25.3.0
      - cachetools==6.1.0
      - click==8.2.1
      - dataclasses==0.6
      - dataclasses-json==0.6.7
      - datasets==4.0.0
      - dill==0.3.8
      - frozenlist==1.7.0
      - fsspec==2025.3.0
      - greenlet==3.2.3
      - hf-xet==1.1.5
      - httpx-sse==0.4.1
      - huggingface-hub==0.33.2
      - ibm-cos-sdk==2.14.2
      - ibm-cos-sdk-core==2.14.2
      - ibm-cos-sdk-s3transfer==2.14.2
      - ibm-watsonx-ai==1.3.30
      - jiter==0.10.0
      - jmespath==1.0.1
      - joblib==1.5.1
      - jsonschema==4.24.0
      - jsonschema-specifications==2025.4.1
      - langchain==0.3.26
      - langchain-community==0.3.27
      - langchain-core==0.3.68
      - langchain-ibm==0.3.15
      - langchain-text-splitters==0.3.8
      - langsmith==0.4.4
      - litellm==1.74.1
      - lomond==0.3.3
      - marshmallow==3.26.1
      - multidict==6.6.3
      - multiprocess==0.70.16
      - mypy-extensions==1.1.0
      - openai==1.94.0
      - orjson==3.10.18
      - pandas==2.2.3
      - pillow==11.3.0
      - propcache==0.3.2
      - pyarrow==20.0.0
      - pydantic-settings==2.10.1
      - python-dateutil==2.9.0.post0
      - python-dotenv==1.1.1
      - pytz==2025.2
      - pyyaml==6.0.2
      - referencing==0.36.2
      - regex==2024.11.6
      - requests==2.32.4
      - requests-toolbelt==1.0.0
      - rpds-py==0.26.0
      - safetensors==0.5.3
      - scikit-learn==1.7.0
      - scipy==1.16.0
      - sentence-transformers==5.0.0
      - six==1.17.0
      - sqlalchemy==2.0.41
      - tabulate==0.9.0
      - tenacity==9.1.2
      - threadpoolctl==3.6.0
      - tiktoken==0.9.0
      - tokenizers==0.21.2
      - transformers==4.53.1
      - typing-inspect==0.9.0
      - typing-inspection==0.4.1
      - tzdata==2025.2
      - xxhash==3.5.0
      - yarl==1.20.1
prefix: /u/coderdoge/miniconda3
